cpan install -fi Log::Log4perl
cpan install -fi YAML
cpan install -fi Bundle::LWP
cpan install -fi LWP::UserAgent
cpan install -fi LWP::Simple
cpan install -fi HTTP::Response
cpan install -fi Getopt::Long
cpan install -fi HTTP::Request
cpan install -fi IO::Select
cpan install -fi HTTP::Cookies
cpan install -fi HTTP::Response
cpan install -fi HTTP::Request::Common
cpan install -fi URI::URL
cpan install -fi IO::Socket::INET
cpan install -fi JSON
cpan install -fi WWW::Mechanize
