sudo cpan install Log::Log4perl
sudo cpan install YAML
sudo cpan install Bundle::LWP
sudo cpan install LWP::UserAgent
sudo cpan install LWP::Simple
sudo cpan install HTTP::Response
sudo cpan install Getopt::Long
sudo cpan install HTTP::Request
sudo cpan install IO::Select
sudo cpan install HTTP::Cookies
sudo cpan install HTTP::Response
sudo cpan install HTTP::Request::Common
sudo cpan install URI::URL
sudo cpan install IO::Socket::INET
sudo cpan install JSON
sudo cpan install WWW::Mechanize
